#!/bin/bash

if $(node -v | grep -Eq ^v4 ); then
    echo "Node installed"
else
    $(sudo apt-get install nodejs)
fi

if $(npm -v | grep -Eq ^2); then
    echo "NPM installed...now check packages"
else
    $(sudo apt-get install npm)
fi

if $(ls node_modules | grep json-duplex-stream >/dev/null 2>&1); then
         echo "modules installed"
else
        $(npm install json-duplex-stream)
        $(npm install stream-meter)
        $(npm install yargs)
        $(npm install bnf)
fi

password=admin
echo "$password"

if [ "$#" = 1 ]; then
     $port = echo "$1"
     echo "$1"
fi

if [ "$#" = 2 ]; then
   $password =  "$2"
   echo "$2"
fi

$(node server.js test $port $password)
echo "{"return_code" : 0}"